# Generated by Django 4.2 on 2023-04-21 13:32

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("pkid_content", models.AutoField(primary_key=True, serialize=False)),
                ("titlecontent", models.CharField(max_length=100)),
                ("description_content", models.CharField(max_length=1000)),
                ("video", models.CharField(max_length=100)),
                ("thumb", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="deactive", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tutors",
            fields=[
                ("pkidtutors", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("pkid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("image", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("pkidplaylist", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("thumb", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="deactive", max_length=20)),
                (
                    "fk_tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.tutors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_content_idlikes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.content",
                    ),
                ),
                (
                    "fk_pklikes_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.users",
                    ),
                ),
                (
                    "fk_tutor_idlikes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.tutors",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="fk_playlist_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applacation1.playlist"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="fk_tutor_idcontent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="applacation1.tutors"
            ),
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("pkid_comments", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=1000)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "fk_content_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.content",
                    ),
                ),
                (
                    "fk_tutor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.tutors",
                    ),
                ),
                (
                    "fk_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_playlist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.playlist",
                    ),
                ),
                (
                    "fk_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applacation1.users",
                    ),
                ),
            ],
        ),
    ]
